{
    {
        console.log("oi")
        {
            {
                {
                    {
                        console.log("tchau")
                        {
                            {
                                {}
                            }
                        }
                    }
                }
            }
        }
    }
}